name: {SNAPNAME}
version: '0.1'
summary: cudnn and cuda library
description: |
  Leverage conda-packages to install cudnn and cuda

grade: devel
base: core20
confinement: strict

parts:
  condapart:
    plugin: make
    make-parameters:
      - -C
      - $SNAPCRAFT_PROJECT_DIR/make

slots:
  {SNAPNAME}:
    content: {SNAPNAME}
    interface: content
    read:
    - /{SNAPNAME}

