name: cudatoolkit-10-2-v1
version: '1.0'
summary: Hello world using ipython from conda packages
description: |
  Leverage conda-packages to install ipython and use it to say "hello world".

grade: devel
base: core20
confinement: strict

apps:
  conda-hello:
    command:
       hello

parts:
  cudatoolkit:
    plugin: conda
    conda-package-files:
      - pkg-file-cudatoolkit.yaml
  hello:
    plugin: dump
    source: .
