name: mkl-2020-2
version: '0.1'
summary: mkl and intel-openmp
description: |
  Leverage conda-packages to install mkl and intel-openmp

grade: devel
base: core20
confinement: strict

parts:
  mkl:
    plugin: make
    make-parameters:
      - -C
      - $SNAPCRAFT_PROJECT_DIR/make

slots:
  mkl:
    content: mkl
    interface: content
    read:
    - /mkl-2020-2

