name: cudnn-7-6-5
version: '0.1'
summary: cudnn and cuda library
description: |
  Leverage conda-packages to install cudnn and cuda

grade: devel
base: core20
confinement: strict

parts:
  cudatoolkit:
    plugin: make
    make-parameters:
      - -C
      - $SNAPCRAFT_PROJECT_DIR/make

slots:
  cudnn765:
    content: cudnn-7-6-5
    interface: content
    read:
    - /cudnn-7-6-5

