name: tensorflow1-15
version: '0.1'
summary: tensorflow1.15
description: |
  Leverage conda-packages to install tensorflow 1.15.0

grade: devel
base: core20
confinement: strict

parts:
  tensorflow:
    plugin: make
    make-parameters:
      - -C
      - $SNAPCRAFT_PROJECT_DIR/make

